[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "testwatch"
version = "1.0.0"
description = "A simple but powerful log monitoring tool for parsing test results"
readme = "README.md"
authors = [
    {name = "gbvk312"}
]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Telecommunications Industry",
    "Topic :: Software Development :: Testing",
]
dependencies = []

[project.scripts]
testwatch = "testwatch.main:main"

[project.entry-points."ttt.plugins"]
testwatch = "testwatch.testwatch_plugin:TestWatchPlugin"

[tool.setuptools.packages.find]
include = ["testwatch*"]


[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.9"
strict = true
ignore_missing_imports = true
